language: c
sudo: false # Allows for faster builds.
os:
  - linux
  - osx
script:
  - make package PACKAGE=ibeasykey-$TRAVIS_OS_NAME.zip
after_success:
  - export COMMIT_TAG="$(git log --format=%h -1)"
  - export COMMIT_MESSAGE="$(git log --pretty=format:"%an - %s" -1)"
  - chmod +x ./travis-push.sh
  - ./travis-push.sh