language: c
sudo: false # Allows for faster builds.
os:
  - linux
  - osx
  - windows
script:
  - make package PACKAGE=libeasykey-$TRAVIS_OS_NAME.zip
after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - export COMMIT_TAG="$(git log --format=%h -1)"
  - export COMMIT_MESSAGE="$(git log --pretty=format:"%an - %s" -1)"
  - cd ..
  - git clone https://${GH_TOKEN}@github.com/arraystock/builds.git
  - mkdir builds/libeasykey/
  - mv ./libeasykey/*.zip ./builds/libeasykey/
  - cd ./builds
  - git add .
  - git commit -m "libeasykey ($TRAVIS_OS_NAME) | Commit $COMMIT_TAG"
  - git push --quiet --set-upstream origin master